training:
  epochs: 10
  batch_size: 2
  amp: true
  use_scaler: true

optimizer:
  type: "Adam"
  lr: 0.0001
  weight_decay: 0.00001

scheduler:
  enabled: false
  type: "StepLR"
  step_size: 30
  gamma: 0.1

augmentation:
  phase_inversion_prob: 0.1
  phase_shift_prob: 0.1
  noise_level: 0.01
